# Generated by Django 5.2.8 on 2025-11-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
