# Generated by Django 5.2.8 on 2025-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='transport_options',
            field=models.TextField(blank=True),
        ),
    ]
