# Generated by Django 5.2.8 on 2025-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tier',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard')], default='Standard', max_length=20),
        ),
    ]
